name: Build and Push to Scaleway Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_API_KEY }}
          registry: rg.fr-par.scw.cloud/nilslair

      - name: Build the Docker image
        run: docker build . -t rg.fr-par.scw.cloud/nilslair/my-nextjs-app

      - name: Push the Docker Image
        run: docker push rg.fr-par.scw.cloud/nilslair/my-nextjs-app

      - name: Deploy container
        uses: httptoolkit/deploy-scaleway-serverless-container-action@v1
        with:
          container_id: 43ead729-3020-426b-be14-ee1aa10e2e7e
          secret_key: ${{ secrets.SCW_SECRET_KEY }}
          registry_image_url: rg.fr-par.scw.cloud/nilslair/my-nextjs-app:latest
          region: fr-par
